name: 'bump-cargo-version'
description: 'A Github action to bump package version in cargo.toml'
author: 'Kento Oki'
inputs:
  cargo-path:
    required: true
    description: 'Specifies the path to cargo.toml in relative or absolute.'
    default: '.'
outputs:
  version:
    description: 'Outputs parsed package version in the specified Cargo.toml'
branding:
  icon: cloud-drizzle
  color: green
runs:
  using: 'node16'
  main: 'dist/index.js'
